"""initial schema

Revision ID: 73ba09c2bcb1
Revises: 
Create Date: 2026-05-19 18:09:34.792127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73ba09c2bcb1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('model_data', sa.Text(), nullable=True),
    sa.Column('trained_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_name')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('nationality', sa.String(length=10), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('atp_id', sa.String(length=50), nullable=True),
    sa.Column('current_ranking', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('raw_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('cached_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('elo_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('surface', sa.String(length=20), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'surface', name='uq_elo_player_surface')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_name', sa.String(length=200), nullable=True),
    sa.Column('tournament_category', sa.String(length=50), nullable=True),
    sa.Column('surface', sa.String(length=20), nullable=True),
    sa.Column('round', sa.String(length=50), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('player1_id', sa.Integer(), nullable=False),
    sa.Column('player2_id', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('score_string', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['player1_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['player2_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_match_date', 'matches', ['date'], unique=False)
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('headline', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sentiment_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('flags', sa.Text(), nullable=True),
    sa.Column('cached_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id')
    )
    op.create_table('match_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('aces', sa.Integer(), nullable=True),
    sa.Column('double_faults', sa.Integer(), nullable=True),
    sa.Column('first_serve_pct', sa.Float(), nullable=True),
    sa.Column('first_serve_won_pct', sa.Float(), nullable=True),
    sa.Column('second_serve_won_pct', sa.Float(), nullable=True),
    sa.Column('bp_faced', sa.Integer(), nullable=True),
    sa.Column('bp_saved', sa.Integer(), nullable=True),
    sa.Column('winners', sa.Integer(), nullable=True),
    sa.Column('unforced_errors', sa.Integer(), nullable=True),
    sa.Column('net_points_won', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_matchstats_match_player', 'match_stats', ['match_id', 'player_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('player1_id', sa.Integer(), nullable=True),
    sa.Column('player2_id', sa.Integer(), nullable=True),
    sa.Column('surface', sa.String(length=20), nullable=True),
    sa.Column('tournament_category', sa.String(length=50), nullable=True),
    sa.Column('p1_win_probability', sa.Float(), nullable=True),
    sa.Column('p2_win_probability', sa.Float(), nullable=True),
    sa.Column('value_bet_player', sa.Integer(), nullable=True),
    sa.Column('edge_percentage', sa.Float(), nullable=True),
    sa.Column('bookmaker_odds_p1', sa.Float(), nullable=True),
    sa.Column('bookmaker_odds_p2', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player1_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['player2_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predictions')
    op.drop_index('ix_matchstats_match_player', table_name='match_stats')
    op.drop_table('match_stats')
    op.drop_table('sentiment_cache')
    op.drop_table('news')
    op.drop_index('ix_match_date', table_name='matches')
    op.drop_table('matches')
    op.drop_table('elo_ratings')
    op.drop_table('raw_cache')
    op.drop_table('players')
    op.drop_table('model_store')
    # ### end Alembic commands ###
